Integrated search with backend
vention-js-lab/ventioners-stayhub-frontend pull request #10
Opened 2024-11-18 13:24 UTC by AKILBEK-UR

2024-11-18 13:28 UTC, purple-mountain commented on src/modules/home/routes/home.route.tsx
> +  const [searchQuery, setsearchQuery] = useSearchParamsState('search', '');
you should name it setSearchQuery

2024-11-18 13:29 UTC, purple-mountain commented on src/modules/home/routes/home.route.tsx
> +      <HeaderComponent setSelectedLocation={setsearchQuery} />
You are not searching by location, so I think the prop should have a different name

2024-11-18 13:31 UTC, purple-mountain commented on src/utils/access-token-store.ts
> +export class AccessTokenStore {
I think this is not used anywhere in this PR?

2024-11-18 13:31 UTC, purple-mountain commented on src/modules/home/routes/home.route.tsx
> +        <PropertyList selectedCategory={selectedCategory} selectedLocation={searchQuery} />
The same here

2024-11-18 13:32 UTC, purple-mountain commented on src/modules/home/components/header/search-bar.tsx
> +  setSelectedLocation: (newState: string) => void;
I think you should also name this prop differently because you are not searching by location.

2024-11-18 18:05 UTC, farrooh requested changes
I left some comments, but I'm a bit confused about how the search is actually working. Is it searching by destination or accommodation name? If you included searching by destination as well, please consider removing this feature, because a filter will be added for that purpose.

2024-11-18 18:05 UTC, farrooh commented on src/modules/home/components/header/search-bar.tsx
> +                fullWidth={true}
It will be considered true even if you don't actually pass `true`.

2024-11-19 11:44 UTC, farrooh approved these changes

2024-11-19 11:45 UTC, MdRasulov approved these changes

2024-11-19 18:40 UTC, merged