[IT]:[17-Property-Card] feat: property card component has been created
vention-js-lab/ventioners-stayhub-frontend pull request #6
Opened 2024-11-12 10:57 UTC by Ismoil-JS

Property card component created ===>
<img width="1440" alt="Screenshot 2024-11-12 at 15 53 31" src="https://github.com/user-attachments/assets/9cad6d59-07b7-4a9d-8f0c-174750268350">
I was needed to use some CSS to do this task. because I use swiper react-ready component, there are more components that are not shown in code, but we can customize them only with css styling, That is why I used some css

2024-11-12 12:57 UTC, MdRasulov requested changes

2024-11-12 12:57 UTC, MdRasulov commented on src/modules/home/components/property/propertyCard.tsx
> +            position: 'absolute',
Please take a look at the comment I left here and follow this flow:
https://github.com/vention-js-lab/ventioners-stayhub-frontend/pull/5#discussion_r1838030972

2024-11-12 12:57 UTC, MdRasulov commented on src/modules/home/components/property/propertyCard.tsx
> +      <style>{`
Lets move this style outside of the component

2024-11-12 14:57 UTC, Ismoil-JS commented on src/modules/home/components/property/propertyCard.tsx
> +          ))}
I am mapping images of apartment, from apartment.images i can take only image

2024-11-13 04:50 UTC, bek-shoyatbek approved these changes

2024-11-13 09:35 UTC, merged